export type PackingData = {
    _id: string;
    customerName: string;
    top: string;
    size: number;
    length: number;
    width: number;
    height: number;
    quantity: number;
    colorCode: string;
    material: string;
}

export const mockData: PackingData[] = [
    {
        _id: '1',
        customerName: 'Customer A',
        top: 'Top A',
        size: 10,
        length: 20,
        width: 15,
        height: 5,
        quantity: 50,
        colorCode: '#FF5733',
        material: 'Material A',
    },
    {
        _id: '2',
        customerName: 'Customer B',
        top: 'Top B',
        size: 12,
        length: 18,
        width: 14,
        height: 6,
        quantity: 30,
        colorCode: '#33FF57',
        material: 'Material B',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
    {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    }, {
        _id: '3',
        customerName: 'Customer C',
        top: 'Top C',
        size: 15,
        length: 22,
        width: 16,
        height: 7,
        quantity: 40,
        colorCode: '#3357FF',
        material: 'Material C',
    },
];